"""
Seed script for 25 base destinations.
Run with: python db/seed_destinations.py
"""
import asyncio
from core.config import settings
from core.supabase_client import db


DESTINATIONS = [
    {
        "slug": "jaipur",
        "name": "Jaipur",
        "state": "Rajasthan",
        "region": "North",
        "lat": 26.9124,
        "lon": 75.7873,
        "description": "The Pink City - known for Hawa Mahal, City Palace, Amber Fort and vibrant bazaars",
        "category": "heritage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1500, "mid": 3500, "premium": 8000},
        "nearest_airport_code": "JAI",
        "nearest_railway_station": "Jaipur Junction",
        "flight_hours_from": {"delhi": 1, "mumbai": 2, "bangalore": 3},
    },
    {
        "slug": "udaipur",
        "name": "Udaipur",
        "state": "Rajasthan",
        "region": "North",
        "lat": 24.5854,
        "lon": 73.7125,
        "description": "City of Lakes - known for Lake Pichola, City Palace and royal heritage",
        "category": "heritage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1800, "mid": 4000, "premium": 9000},
        "nearest_airport_code": "UDR",
        "nearest_railway_station": "Udaipur City",
        "flight_hours_from": {"delhi": 1.5, "mumbai": 2, "bangalore": 3},
    },
    {
        "slug": "jodhpur",
        "name": "Jodhpur",
        "state": "Rajasthan",
        "region": "North",
        "lat": 26.2389,
        "lon": 73.0243,
        "description": "Blue City - dominated by Mehrangarh Fort, known for old blue houses",
        "category": "heritage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1400, "mid": 3000, "premium": 7000},
        "nearest_airport_code": "JDH",
        "nearest_railway_station": "Jodhpur Junction",
        "flight_hours_from": {"delhi": 1.5, "mumbai": 2, "bangalore": 3},
    },
    {
        "slug": "jaisalmer",
        "name": "Jaisalmer",
        "state": "Rajasthan",
        "region": "North",
        "lat": 26.2976,
        "lon": 70.9178,
        "description": "Golden City - Thar Desert, sand dunes, camel safaris and Jain temples",
        "category": "heritage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 3,
        "difficulty": "moderate",
        "avg_daily_budget_inr": {"budget": 1600, "mid": 3500, "premium": 7500},
        "nearest_airport_code": "JSA",
        "nearest_railway_station": "Jaisalmer",
        "flight_hours_from": {"delhi": 2, "mumbai": 2.5, "bangalore": 4},
    },
    {
        "slug": "pushkar",
        "name": "Pushkar",
        "state": "Rajasthan",
        "region": "North",
        "lat": 26.4897,
        "lon": 74.5501,
        "description": "Holy city with Pushkar Lake, Brahma Temple and famous camel fair",
        "category": "pilgrimage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1000, "mid": 2500, "premium": 5000},
        "nearest_airport_code": "JAI",
        "nearest_railway_station": "Ajmer Junction",
        "flight_hours_from": {"delhi": 1, "mumbai": 2, "bangalore": 3},
    },
    {
        "slug": "goa-north",
        "name": "Goa North (Calangute)",
        "state": "Goa",
        "region": "West",
        "lat": 15.542,
        "lon": 73.7594,
        "description": "Popular beach destination with water sports, nightlife and Portuguese heritage",
        "category": "beach",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 4,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 2000, "mid": 4500, "premium": 10000},
        "nearest_airport_code": "GOI",
        "nearest_railway_station": "Thivim",
        "flight_hours_from": {"delhi": 2.5, "mumbai": 1, "bangalore": 1},
    },
    {
        "slug": "goa-south",
        "name": "Goa South (Palolem)",
        "state": "Goa",
        "region": "West",
        "lat": 15.01,
        "lon": 74.02,
        "description": "Relaxed beach destination with pristine beaches and yoga retreats",
        "category": "beach",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 4,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1800, "mid": 4000, "premium": 9000},
        "nearest_airport_code": "GOI",
        "nearest_railway_station": "Canacona",
        "flight_hours_from": {"delhi": 2.5, "mumbai": 1, "bangalore": 1},
    },
    {
        "slug": "varkala",
        "name": "Varkala",
        "state": "Kerala",
        "region": "South",
        "lat": 8.7378,
        "lon": 76.715,
        "description": "Cliff-side beach destination with Ayurveda and spiritual retreats",
        "category": "beach",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1500, "mid": 3500, "premium": 7000},
        "nearest_airport_code": "TRV",
        "nearest_railway_station": "Varkala",
        "flight_hours_from": {"delhi": 3, "mumbai": 2, "bangalore": 1},
    },
    {
        "slug": "kovalam",
        "name": "Kovalam",
        "state": "Kerala",
        "region": "South",
        "lat": 8.393,
        "lon": 76.978,
        "description": "Beach destination with lighthouse, surfing and Ayurvedic spas",
        "category": "beach",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1600, "mid": 3800, "premium": 8000},
        "nearest_airport_code": "TRV",
        "nearest_railway_station": "Thiruvananthapuram",
        "flight_hours_from": {"delhi": 3, "mumbai": 2, "bangalore": 1},
    },
    {
        "slug": "munnar",
        "name": "Munnar",
        "state": "Kerala",
        "region": "South",
        "lat": 10.0889,
        "lon": 77.0595,
        "description": "Hill station with tea plantations, Neelakurinji flowers and cool climate",
        "category": "mountains",
        "best_months": [9, 10, 11, 12, 1, 2, 3, 4, 5],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1500, "mid": 3500, "premium": 7500},
        "nearest_airport_code": "COK",
        "nearest_railway_station": "Aluva",
        "flight_hours_from": {"delhi": 3.5, "mumbai": 2, "bangalore": 1},
    },
    {
        "slug": "coorg",
        "name": "Coorg",
        "state": "Karnataka",
        "region": "South",
        "lat": 12.3376,
        "lon": 75.8069,
        "description": "Scotland of India - coffee plantations, spices and misty hills",
        "category": "mountains",
        "best_months": [9, 10, 11, 12, 1, 2, 3, 4, 5],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1800, "mid": 4000, "premium": 8500},
        "nearest_airport_code": "IXE",
        "nearest_railway_station": "Mysore",
        "flight_hours_from": {"delhi": 3, "mumbai": 1.5, "bangalore": 1},
    },
    {
        "slug": "hampi",
        "name": "Hampi",
        "state": "Karnataka",
        "region": "South",
        "lat": 15.335,
        "lon": 76.46,
        "description": "UNESCO World Heritage site with ruins of Vijayanagara Empire",
        "category": "heritage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 2,
        "difficulty": "moderate",
        "avg_daily_budget_inr": {"budget": 1200, "mid": 2800, "premium": 6000},
        "nearest_airport_code": "HBK",
        "nearest_railway_station": "Hospet",
        "flight_hours_from": {"delhi": 3, "mumbai": 2, "bangalore": 1},
    },
    {
        "slug": "pondicherry",
        "name": "Pondicherry",
        "state": "Puducherry",
        "region": "South",
        "lat": 11.9416,
        "lon": 79.8083,
        "description": "French colonial city with beaches, ashrams and colonial architecture",
        "category": "city",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1500, "mid": 3500, "premium": 7000},
        "nearest_airport_code": "PNY",
        "nearest_railway_station": "Puducherry",
        "flight_hours_from": {"delhi": 3, "mumbai": 2, "bangalore": 0.5},
    },
    {
        "slug": "manali",
        "name": "Manali",
        "state": "Himachal Pradesh",
        "region": "North",
        "lat": 32.2432,
        "lon": 77.1892,
        "description": "Popular hill station with Rohtang Pass, temples and adventure sports",
        "category": "mountains",
        "best_months": [3, 4, 5, 6, 9, 10, 11],
        "avg_trip_duration_days": 4,
        "difficulty": "moderate",
        "avg_daily_budget_inr": {"budget": 1800, "mid": 4000, "premium": 8500},
        "nearest_airport_code": "KUU",
        "nearest_railway_station": "Kullu",
        "flight_hours_from": {"delhi": 1, "mumbai": 2.5, "bangalore": 3.5},
    },
    {
        "slug": "shimla",
        "name": "Shimla",
        "state": "Himachal Pradesh",
        "region": "North",
        "lat": 31.1048,
        "lon": 77.1734,
        "description": "Queen of Hills - British colonial architecture and mountain railways",
        "category": "mountains",
        "best_months": [3, 4, 5, 6, 9, 10, 11],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1600, "mid": 3500, "premium": 7500},
        "nearest_airport_code": "SLV",
        "nearest_railway_station": "Shimla",
        "flight_hours_from": {"delhi": 1, "mumbai": 2.5, "bangalore": 3.5},
    },
    {
        "slug": "dharamshala",
        "name": "Dharamshala",
        "state": "Himachal Pradesh",
        "region": "North",
        "lat": 32.219,
        "lon": 76.3234,
        "description": "Home of Dalai Lama, Tibetan culture and scenic Kangra valley",
        "category": "mountains",
        "best_months": [3, 4, 5, 6, 9, 10, 11],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1500, "mid": 3500, "premium": 7000},
        "nearest_airport_code": "DHM",
        "nearest_railway_station": "Kangra",
        "flight_hours_from": {"delhi": 1.5, "mumbai": 2.5, "bangalore": 3.5},
    },
    {
        "slug": "spiti-valley",
        "name": "Spiti Valley",
        "state": "Himachal Pradesh",
        "region": "North",
        "lat": 32.45,
        "lon": 78.05,
        "description": "Remote Himalayan desert with monasteries, high passes and stark beauty",
        "category": "mountains",
        "best_months": [6, 7, 8, 9],
        "avg_trip_duration_days": 7,
        "difficulty": "difficult",
        "avg_daily_budget_inr": {"budget": 2000, "mid": 4500, "premium": 10000},
        "nearest_airport_code": "KUU",
        "nearest_railway_station": "Shimla",
        "flight_hours_from": {"delhi": 1.5, "mumbai": 3, "bangalore": 4},
    },
    {
        "slug": "darjeeling",
        "name": "Darjeeling",
        "state": "West Bengal",
        "region": "East",
        "lat": 27.041,
        "lon": 88.2619,
        "description": "Toy train UNESCO site, tea gardens and Himalayan views",
        "category": "mountains",
        "best_months": [3, 4, 5, 9, 10, 11],
        "avg_trip_duration_days": 3,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1500, "mid": 3500, "premium": 7000},
        "nearest_airport_code": "IXB",
        "nearest_railway_station": "Darjeeling",
        "flight_hours_from": {"delhi": 2, "mumbai": 3, "bangalore": 3},
    },
    {
        "slug": "gangtok",
        "name": "Gangtok",
        "state": "Sikkim",
        "region": "East",
        "lat": 27.3313,
        "lon": 88.6138,
        "description": "Capital of Sikkim with monasteries, MG Road and mountain views",
        "category": "mountains",
        "best_months": [3, 4, 5, 9, 10, 11],
        "avg_trip_duration_days": 4,
        "difficulty": "moderate",
        "avg_daily_budget_inr": {"budget": 1800, "mid": 4000, "premium": 8500},
        "nearest_airport_code": "PYG",
        "nearest_railway_station": "New Jalpaiguri",
        "flight_hours_from": {"delhi": 2, "mumbai": 3, "bangalore": 3.5},
    },
    {
        "slug": "varanasi",
        "name": "Varanasi",
        "state": "Uttar Pradesh",
        "region": "North",
        "lat": 25.3176,
        "lon": 82.9739,
        "description": "Oldest city in the world, sacred Ganges ghats and spiritual capital",
        "category": "pilgrimage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1200, "mid": 2800, "premium": 6000},
        "nearest_airport_code": "VNS",
        "nearest_railway_station": "Varanasi Junction",
        "flight_hours_from": {"delhi": 1.5, "mumbai": 2.5, "bangalore": 3},
    },
    {
        "slug": "agra",
        "name": "Agra",
        "state": "Uttar Pradesh",
        "region": "North",
        "lat": 27.1767,
        "lon": 78.0081,
        "description": "Home to Taj Mahal, Agra Fort and Fatehpur Sikri",
        "category": "heritage",
        "best_months": [10, 11, 12, 1, 2, 3],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1400, "mid": 3000, "premium": 6500},
        "nearest_airport_code": "AGR",
        "nearest_railway_station": "Agra Cantt",
        "flight_hours_from": {"delhi": 0.5, "mumbai": 2, "bangalore": 2.5},
    },
    {
        "slug": "andaman-islands",
        "name": "Andaman Islands (Port Blair)",
        "state": "Andaman & Nicobar",
        "region": "Islands",
        "lat": 11.7181,
        "lon": 92.7206,
        "description": "Cellular Jail, Radhanagar Beach and diving in emerald waters",
        "category": "beach",
        "best_months": [10, 11, 12, 1, 2, 3, 4],
        "avg_trip_duration_days": 5,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 2500, "mid": 5000, "premium": 12000},
        "nearest_airport_code": "IXZ",
        "nearest_railway_station": "None (island)",
        "flight_hours_from": {"delhi": 4, "mumbai": 4, "bangalore": 3.5},
    },
    {
        "slug": "kaziranga",
        "name": "Kaziranga",
        "state": "Assam",
        "region": "East",
        "lat": 26.5958,
        "lon": 93.1713,
        "description": "One-horned rhinoceros sanctuary with jeep safaris",
        "category": "wildlife",
        "best_months": [11, 12, 1, 2, 3, 4],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 2000, "mid": 4500, "premium": 9000},
        "nearest_airport_code": "VTZ",
        "nearest_railway_station": "Furkating",
        "flight_hours_from": {"delhi": 3, "mumbai": 4, "bangalore": 4},
    },
    {
        "slug": "ranthambore",
        "name": "Ranthambore",
        "state": "Rajasthan",
        "region": "North",
        "lat": 25.0202,
        "lon": 76.6019,
        "description": "Tiger reserve with ancient fort and wildlife safaris",
        "category": "wildlife",
        "best_months": [10, 11, 12, 1, 2, 3, 4],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1800, "mid": 4000, "premium": 8000},
        "nearest_airport_code": "JAI",
        "nearest_railway_station": "Sawai Madhopur",
        "flight_hours_from": {"delhi": 1, "mumbai": 2, "bangalore": 3},
    },
    {
        "slug": "jim-corbett",
        "name": "Jim Corbett",
        "state": "Uttarakhand",
        "region": "North",
        "lat": 29.53,
        "lon": 78.89,
        "description": "Oldest national park in India with tiger sightings and river rafting",
        "category": "wildlife",
        "best_months": [11, 12, 1, 2, 3, 4, 5],
        "avg_trip_duration_days": 2,
        "difficulty": "easy",
        "avg_daily_budget_inr": {"budget": 1800, "mid": 4000, "premium": 8500},
        "nearest_airport_code": "DED",
        "nearest_railway_station": "Ramnagar",
        "flight_hours_from": {"delhi": 1, "mumbai": 2.5, "bangalore": 3},
    },
]


async def seed_destinations():
    """Insert or upsert 25 base destinations into the database."""
    print("=" * 60)
    print("SEEDING 25 DESTINATIONS")
    print("=" * 60)

    inserted = 0
    updated = 0

    for dest in DESTINATIONS:
        try:
            response = db.table("destinations").upsert(
                dest,
                on_conflict="slug",
                returning="representation"
            ).execute()

            # Check if it's an insert or update based on response
            if response.data:
                if response.count == 1:
                    print(f"  ✓ {dest['name']} ({dest['slug']}) - {dest['state']}")
                    inserted += 1
                else:
                    print(f"  ~ {dest['name']} ({dest['slug']}) - updated")
                    updated += 1
            else:
                print(f"  ~ {dest['name']} ({dest['slug']}) - skipped")
        except Exception as e:
            print(f"  ✗ {dest['name']} ({dest['slug']}) - ERROR: {e}")

    print()
    print("=" * 60)
    print(f"DONE! Inserted: {inserted}, Updated: {updated}")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(seed_destinations())