-- Disable Row Level Security for all tables (for seeding)
-- Run this after 001_initial_schema.sql

ALTER TABLE destinations DISABLE ROW LEVEL SECURITY;
ALTER TABLE places DISABLE ROW LEVEL SECURITY;
ALTER TABLE hotels DISABLE ROW LEVEL SECURITY;
ALTER TABLE hotel_price_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE flights DISABLE ROW LEVEL SECURITY;
ALTER TABLE local_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE news_alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE blogs_and_guides DISABLE ROW LEVEL SECURITY;
ALTER TABLE weather_cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE search_cache DISABLE ROW LEVEL SECURITY;